/*
    Nil RTOS - Copyright (C) 2012 Giovanni Di Sirio.

    This file is part of Nil RTOS.

    Nil RTOS is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    Nil RTOS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file    nilcore.c
 * @brief   Nil RTOS AVR port main source file.
 *
 * @defgroup AVR_CORE AVR core
 * @{
 */

#include "nil.h"

/*===========================================================================*/
/* Module local definitions.                                                 */
/*===========================================================================*/

/*===========================================================================*/
/* Module exported variables.                                                */
/*===========================================================================*/

/*===========================================================================*/
/* Module local variables.                                                   */
/*===========================================================================*/

/*===========================================================================*/
/* Module local functions.                                                   */
/*===========================================================================*/

/*===========================================================================*/
/* Module interrupt handlers.                                                */
/*===========================================================================*/

/*===========================================================================*/
/* Module exported functions.                                                */
/*===========================================================================*/

/**
 * @brief   Performs a context switch between two threads.
 * @details This is the most critical code in any port, this function
 *          is responsible for the context switch between 2 threads.
 * @note    The implementation of this code affects <b>directly</b> the context
 *          switch performance so optimize here as much as you can.
 
 * GG: Arduino uno chip is ATmega328P 
 * https://en.wikipedia.org/wiki/ATmega328 
 * https://en.wikipedia.org/wiki/Atmel_AVR_instruction_set
 * ref https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-7810-Automotive-Microcontrollers-ATmega328P_Datasheet.pdf
 
 * naked: Use this attribute on the ARM, AVR, IP2K, RX and SPU ports to indicate that the specified function does not need prologue/epilogue 
 * sequences generated by the compiler.
 
 How this is called....? r22:r25 are two 16 bit pointers used for making the switch

inside nilThdSleep

     2f0:	0c c0       	rjmp	.+24     	; 0x30a <nilThdSleep+0x5a>
     ; GG Store register to some RAM
     2f2:	90 93 04 01 	sts	0x0104, r25	; 0x800104 <nil+0x3>
     2f6:	80 93 03 01 	sts	0x0103, r24	; 0x800103 <nil+0x2>
     2fa:	90 93 02 01 	sts	0x0102, r25	; 0x800102 <nil+0x1>
     2fe:	80 93 01 01 	sts	0x0101, r24	; 0x800101 <nil>
     302:	0e 94 11 01 	call	0x222	; 0x222 <_port_switch>
     306:	78 94       	sei
     308:	08 95       	ret

Inside __vector_14
Store reg 24,25 to RAM 101 e 102
    12d0:	90 93 02 01 	sts	0x0102, r25	; 0x800102 <nil+0x1>
    12d4:	80 93 01 01 	sts	0x0101, r24	; 0x800101 <nil>
    12d8:	0e 94 11 01 	call	0x222	; 0x222 <_port_switch>



 * @param[in] ntp       the thread to be switched in
 * @param[in] otp       the thread to be switched out
 */
#if !defined(__DOXYGEN__)
__attribute__((naked))
#endif
void _port_switch(thread_t *ntp, thread_t *otp) {

  asm volatile ("push    r2");
  asm volatile ("push    r3");
  asm volatile ("push    r4");
  asm volatile ("push    r5");
  asm volatile ("push    r6");
  asm volatile ("push    r7");
  asm volatile ("push    r8");
  asm volatile ("push    r9");
  asm volatile ("push    r10");
  asm volatile ("push    r11");
  asm volatile ("push    r12");
  asm volatile ("push    r13");
  asm volatile ("push    r14");
  asm volatile ("push    r15");
  asm volatile ("push    r16");
  asm volatile ("push    r17");
  asm volatile ("push    r28");
  asm volatile ("push    r29");
    
  // R30, R31 is register Z 8-bit each
  // The first 64 I/O registers are accessible through both the I/O and the data address space. 
  // 
  // MOVW Rd, Rr / Copy register word Rd+1:Rd <- Rr+1:Rr
  // ? This code put on register Z (r31:r30 ) the content of r23:r22 
  // To prepare stack pointer switch
  
  asm volatile ("movw    r30, r22");
    
  // SP is 0x3E:0x3D so this instruction read the SP in r0  and store it in the location pointed by Z register (indirect)
  // Z register is a 16bit pointer in r31,r30
  
    
  asm volatile ("in      r0, 0x3d");
  asm volatile ("std     Z+0, r0");
  asm volatile ("in      r0, 0x3e");
  asm volatile ("std     Z+1, r0");

  // Load Z low register from r25:r24 and load SP from there always using r0 register to support this transfer
    
  asm volatile ("movw    r30, r24");
  asm volatile ("ldd     r0, Z+0");
  asm volatile ("out     0x3d, r0");
  asm volatile ("ldd     r0, Z+1");
  asm volatile ("out     0x3e, r0");

  // 
  // pop the data stored in the SP
  // 
  asm volatile ("pop     r29");
  asm volatile ("pop     r28");
  asm volatile ("pop     r17");
  asm volatile ("pop     r16");
  asm volatile ("pop     r15");
  asm volatile ("pop     r14");
  asm volatile ("pop     r13");
  asm volatile ("pop     r12");
  asm volatile ("pop     r11");
  asm volatile ("pop     r10");
  asm volatile ("pop     r9");
  asm volatile ("pop     r8");
  asm volatile ("pop     r7");
  asm volatile ("pop     r6");
  asm volatile ("pop     r5");
  asm volatile ("pop     r4");
  asm volatile ("pop     r3");
  asm volatile ("pop     r2");
  asm volatile ("ret");
}

/**
 * @brief   Start a thread by invoking its work function.
 * @details If the work function returns @p chThdExit() is automatically
 *          invoked.
 */
#if !defined(__DOXYGEN__)
__attribute__((naked))
#endif
void _port_thread_start(void) {

  nilSysUnlock();
    
  // this code make an indirect call using location inside Z (r31,r30)
  asm volatile ("movw    r24, r4");
  asm volatile ("movw    r30, r2");
  asm volatile ("icall");

  nilDbgAssert(true, "_port_thread_start(), #1", "thread returned");
}

/**
 * @brief   Halts the system.
 * @details This function is invoked by the operating system when an
 *          unrecoverable error is detected (for example because a programming
 *          error in the application code that triggers an assertion while in
 *          debug mode).
 * @note    The function is declared as a weak symbol, it is possible to
 *          redefine it in your application code.
 */
#if !defined(__DOXYGEN__)
__attribute__((naked, weak))
#endif
void port_halt(void) {

  port_disable();
  while (true) {
  }
}

/** @} */
